export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";
export const revalidate = 0;
import { Geist, Geist_Mono } from "next/font/google";
// import 'flowbite';
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Footer from "@/component/Footer";
import Clientlayout from "@/component/Clientlayout";
import { CartProvider } from "@/component/CartContext";
import SearchResult from "@/component/SearchResult";
import '@fortawesome/fontawesome-free/css/all.min.css';
import SessionWrapper from "@/component/SessionWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          <SessionWrapper>
            <CartProvider>
              <SearchResult />
              <Clientlayout>{children}</Clientlayout>
              <Footer />
            </CartProvider>
          </SessionWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}


